### PR TITLE
Add zh-CN and zh-TW translation

### PR DESCRIPTION
**Pull request by LarryLuTW**
https://app.asana.com/0/1166821020652777/1201575618243328/f

### CODE REVIEW

**Review by silgal — APPROVED** [review]
I tried the github edit feature and pushed an extra commit if you don't mind.

**Comment by silgal** [comment]
> I tried the github edit feature and pushed an extra commit if you don't mind.

Wait, that should be a fixup

**Comment by LarryLuTW** [comment]
Cool, thanks. Let me squash them.

**Comment by silgal** [comment]
> Cool, thanks. Let me squash them

thanks

**Pull request merged**
